#!/bin/bash

components=$(ls -1 src/components)
components=${components/ /$'\n'/}

echo $components

for filename in ./projects/*; do
	cmd="./CR ${filename} ./built/${filename} ./src/components/${components}"
	echo $cmd
	$cmd
done

cmd="./CR index.html built/index.html ./src/components/${components}"
echo $cmd
$cmd
